name: testsuite

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3

      - name: Install System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libio-fdpass-perl libio-socket-ssl-perl libnet-ssleay-perl

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Check
        run: |
          if ! make check; then
            for dir in tests/testsuite.dir/*
            do
              echo "Test $(basename $dir)"
              for file in testsuite.log xscript.log pound.log pound.cfi pound.cfg input
              do
                if test -f $dir/$file; then
                  echo "File $file"
                  echo "File $file"|sed -e 's/./=/g'
                  cat $dir/$file
                fi
              done
            done
            false
          fi

  linux-dynamic:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3

      - name: Install System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libio-fdpass-perl libio-socket-ssl-perl libnet-ssleay-perl libadns1-dev libnet-dns-perl

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: ./configure --enable-dns-tests

      - name: Build
        run: make

      - name: Check
        run: |
          if ! make check; then
            for dir in tests/testsuite.dir/*
            do
              echo "Test $(basename $dir)"
              for file in testsuite.log xscript.log pound.log pound.cfi pound.cfg input
              do
                if test -f $dir/$file; then
                  echo "File $file"
                  echo "File $file"|sed -e 's/./=/g'
                  cat $dir/$file
                fi
              done
            done
            false
          fi

  linux-periodic:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3

      - name: Install System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libio-fdpass-perl libio-socket-ssl-perl libnet-ssleay-perl libadns1-dev libnet-dns-perl

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: ./configure --enable-dns-tests --without-inotify

      - name: Build
        run: make

      - name: Check
        run: |
          if ! make check; then
            for dir in tests/testsuite.dir/*
            do
              echo "Test $(basename $dir)"
              for file in testsuite.log xscript.log pound.log pound.cfi pound.cfg input
              do
                if test -f $dir/$file; then
                  echo "File $file"
                  echo "File $file"|sed -e 's/./=/g'
                  cat $dir/$file
                fi
              done
            done
            false
          fi

  linux-lua:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3

      - name: Install System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libio-fdpass-perl libio-socket-ssl-perl libnet-ssleay-perl liblua5.4-dev

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Check
        run: |
          if ! make check; then
            for dir in tests/testsuite.dir/*
            do
              echo "Test $(basename $dir)"
              for file in testsuite.log xscript.log pound.log pound.cfi pound.cfg input
              do
                if test -f $dir/$file; then
                  echo "File $file"
                  echo "File $file"|sed -e 's/./=/g'
                  cat $dir/$file
                fi
              done
            done
            false
          fi
